title: "Tommaso Tulkens"
description: "Academic website. Research, teaching, publications, and contact information."
theme: minima

header_pages:
  - index.md
  - research.md
  - teaching.md
  - other.md


plugins:
  - jekyll-sitemap
