title: "Tommaso Tulkens"
description: "PhD candidate in economics at Erasmus university Rotterdam"
theme: minima

header_pages:
  - index.md
  - research.md
  - teaching.md
  - other.md

plugins:
  - jekyll-sitemap

include: ["_includes/head-custom.html"]